// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/Button.vue')['default']
    Mailgo: typeof import('./src/components/Mailgo.vue')['default']
    Spinner: typeof import('./src/components/Spinner.vue')['default']
  }
}

export { }
