// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'DaimButtonStories': typeof import("../../src/components/Button.stories.js")['default'],
    'DaimButton': typeof import("../../src/components/Button.vue")['default'],
    'DaimMailgo': typeof import("../../src/components/Mailgo.vue")['default'],
    'DaimSpinner': typeof import("../../src/components/Spinner.vue")['default'],
    'NuxtWelcome': typeof import("../../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'NuxtLayout': typeof import("../../node_modules/nuxt3/dist/app/components/layout")['default'],
    'NuxtErrorBoundary': typeof import("../../node_modules/nuxt3/dist/app/components/nuxt-error-boundary")['default'],
    'ClientOnly': typeof import("../../node_modules/nuxt3/dist/app/components/client-only")['default'],
    'NuxtLink': typeof import("../../node_modules/nuxt3/dist/app/components/nuxt-link")['default']
    'LazyDaimButtonStories': typeof import("../../src/components/Button.stories.js")['default'],
    'LazyDaimButton': typeof import("../../src/components/Button.vue")['default'],
    'LazyDaimMailgo': typeof import("../../src/components/Mailgo.vue")['default'],
    'LazyDaimSpinner': typeof import("../../src/components/Spinner.vue")['default'],
    'LazyNuxtWelcome': typeof import("../../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'LazyNuxtLayout': typeof import("../../node_modules/nuxt3/dist/app/components/layout")['default'],
    'LazyNuxtErrorBoundary': typeof import("../../node_modules/nuxt3/dist/app/components/nuxt-error-boundary")['default'],
    'LazyClientOnly': typeof import("../../node_modules/nuxt3/dist/app/components/client-only")['default'],
    'LazyNuxtLink': typeof import("../../node_modules/nuxt3/dist/app/components/nuxt-link")['default']
  }
}
export const DaimButtonStories: typeof import("../../src/components/Button.stories.js")['default']
export const DaimButton: typeof import("../../src/components/Button.vue")['default']
export const DaimMailgo: typeof import("../../src/components/Mailgo.vue")['default']
export const DaimSpinner: typeof import("../../src/components/Spinner.vue")['default']
export const NuxtWelcome: typeof import("../../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../../node_modules/nuxt3/dist/app/components/layout")['default']
export const NuxtErrorBoundary: typeof import("../../node_modules/nuxt3/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../../node_modules/nuxt3/dist/app/components/client-only")['default']
export const NuxtLink: typeof import("../../node_modules/nuxt3/dist/app/components/nuxt-link")['default']
export const LazyDaimButtonStories: typeof import("../../src/components/Button.stories.js")['default']
export const LazyDaimButton: typeof import("../../src/components/Button.vue")['default']
export const LazyDaimMailgo: typeof import("../../src/components/Mailgo.vue")['default']
export const LazyDaimSpinner: typeof import("../../src/components/Spinner.vue")['default']
export const LazyNuxtWelcome: typeof import("../../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../../node_modules/nuxt3/dist/app/components/layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../../node_modules/nuxt3/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../../node_modules/nuxt3/dist/app/components/client-only")['default']
export const LazyNuxtLink: typeof import("../../node_modules/nuxt3/dist/app/components/nuxt-link")['default']
export const componentNames: string[]
